### PR TITLE
Chore: icons migration

### PR DESCRIPTION
**Pull request by jey-exp**
Migrated all icons from react-icons to lucide-icons
This should improve the performance a bit. 
#53 #

### CODE REVIEW

**Comment by realChakrawarti** [comment]
Thank you for raising the PR. 🙌🏽 

Here are few things, if you could address them.

1. As you can see in the screenshot shared, the `react-icons` is still referenced in the `package.json`. Could remove it and re-generate the lockfile. Leave out `DEPENDENCIES.md` file.
image

2. There are multiple components where `lucide-react` icons are used directly, it would nice if you could move these to `icons.tsx` file and import the icon in the respective component exclusively from `icons.tsx` file. It was one of the requirement of the ticket.
image

3.  I could see that you have merged the `dev` branch into your branch after checking out from the `main` branch. Could you clean that up? Simplest way is just run this command `git rebase dev`. This should make the commits linear. Apply the above requested changes, commit it and while pushing, simply force-push it `git push -f`.

If you have an queries, feel free to ask.

**Comment by jey-exp** [comment]
So sorry for that, seems like a lot of mistake. (I am student and just started my open source journey)

I will change all imports to use the exports of icons.tsx, regenerate lock.json file

And again sorry for the issues with merging, I checkout from main, made the changes and raised the PR to dev branch :(
Will this get solved if I run git rebase dev? I am not good at such things, learning through mistakes.

**Comment by realChakrawarti** [comment]
> So sorry for that, seems like a lot of mistake. (I am student and just started my open source journey)

Don't worry 😄, we all start from somewhere. At least you started, that's a milestone in itself. 

> I will change all imports to use the exports of icons.tsx, regenerate lock.json file

👍🏽

> And again sorry for the issues with merging, I checkout from main, made the changes and raised the PR to dev branch :( Will this get solved if I run git rebase dev? I am not good at such things, learning through mistakes.

Yes, `git rebase dev` on your branch should fix this issue. It will put your commit on top of the `dev` branch's last commit. And when you force push the changes, in the PR will only see you commits in commits tabs.

In future, create a branch from `dev` instead. I will also update the `README.md`. Didn't really considered someone would be contributing. 😁

**Comment by jey-exp** [comment]
Actually I didn't yet regenerate the lock. file
I should have marked it as draft. Will fix it in raising my next PR! 

Also I do have doubt about how to raise the PR directly to the issue that you assigned to me, I mentioned that Issue #53 in this, but seems like this created a new issue #56.

**Pull request merged**
